apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-rc
spec:
  replicas: 3
  selector:
    app: devopsnginx
  template:
    metadata:
      labels:
        app: devopsnginx
    spec:
      containers:
      - name: hello-pod
        image: nginx
        ports:
        - containerPort: 80
